name: Build and Analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Install StyleCop.Analyzers
      run: |
        dotnet add Core/Core.csproj package StyleCop.Analyzers
        dotnet add Infrastructure/Infrastructure.csproj package StyleCop.Analyzers
        dotnet add Api/Api.csproj package StyleCop.Analyzers

    - name: Install Microsoft.CodeAnalysis.NetAnalyzers
      run: |
        dotnet add Core/Core.csproj package Microsoft.CodeAnalysis.NetAnalyzers
        dotnet add Infrastructure/Infrastructure.csproj package Microsoft.CodeAnalysis.NetAnalyzers
        dotnet add Api/Api.csproj package Microsoft.CodeAnalysis.NetAnalyzers

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore /p:TreatWarningsAsErrors=true

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

    - name: Run Code Analysis
      run: dotnet build /p:TreatWarningsAsErrors=true /p:EnforceCodeStyleInBuild=true